search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
search/src/main/res/values/strings.xml

1. Fixed localized default string

Mobileapps 868

---

search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt

1. Selected value must be retained on orientation change

Mobileapps 871

---

search/src/main/kotlin/com/alfresco/content/search/ListViewFilterChips.kt
search/src/main/kotlin/com/alfresco/content/search/components/ComponentCreateViewModel.kt
search/src/main/kotlin/com/alfresco/content/search/components/CreateComponentsSheet.kt
search/src/main/kotlin/com/alfresco/content/search/components/DatePickerBuilder.kt
search/src/main/res/drawable/ic_date_range_calendar.xml
search/src/main/res/layout/sheet_component_create.xml
search/src/main/res/layout/view_date_range_component.xml
search/src/main/res/layout/view_number_range_component.xml
search/src/main/res/layout/view_text_component.xml
search/src/main/res/values/strings.xml

Mobileapps 897

---

data/src/main/kotlin/com/alfresco/content/data/SearchRepository.kt
search/src/main/kotlin/com/alfresco/content/search/ListViewFilterChips.kt
search/src/main/kotlin/com/alfresco/content/search/SearchChipCategory.kt
search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt

1. fixed contextual search wrong text
2. scroll to first chip after reset

Mobileapps 927

---

auth/src/main/res/values-de/strings.xml
auth/src/main/res/values-fr/strings.xml
auth/src/main/res/values-it/strings.xml
auth/src/main/res/values-nl/strings.xml
search/src/main/kotlin/com/alfresco/content/search/components/DatePickerBuilder.kt

fixed fromDate selection as not able to pick same as toDate

Mobileapps- 929

---

search/src/main/res/layout/fragment_recent_search.xml
search/src/main/res/layout/list_search_filter_pop_up.xml
search/src/main/res/layout/view_recent_search_row.xml

1. revert UI margin on search screen

Mobileapps-933

---

search/src/main/kotlin/com/alfresco/content/search/components/CreateComponentsSheet.kt
search/src/main/res/values-de/strings.xml
search/src/main/res/values-es/strings.xml
search/src/main/res/values-fr/strings.xml
search/src/main/res/values-it/strings.xml
search/src/main/res/values-nl/strings.xml
search/src/main/res/values/strings.xml

update localisation same as adf

Mobileapps-939

---

search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
search/src/main/kotlin/com/alfresco/content/search/components/ComponentBuilder.kt
search/src/main/kotlin/com/alfresco/content/search/components/ComponentCreateViewModel.kt
search/src/main/kotlin/com/alfresco/content/search/components/CreateComponentsSheet.kt
search/src/main/kotlin/com/alfresco/content/search/components/DatePickerBuilder.kt
search/src/main/kotlin/com/alfresco/content/search/components/ListViewCheckRow.kt
search/src/main/kotlin/com/alfresco/content/search/components/ListViewRadioRow.kt
search/src/main/res/layout/view_check_list_row.xml
search/src/main/res/layout/view_radio_list_row.xml
theme/src/main/res/values/styles.xml

1. Dropdown should close on second tap
2. Two drawer open when user select two chip at a time
3. Two calendar open when user click From, To date very quickly
4. Whole row should work as check box
5. Updated values for content size range is not reflecting on chip if user only update the from value
6. Other chips also get unselected when user unselect the contextual chip

Mobileapps 960

---

data/src/main/kotlin/com/alfresco/content/data/FacetContext.kt
search/src/main/kotlin/com/alfresco/content/search/ChipComponentType.kt
search/src/main/kotlin/com/alfresco/content/search/ListViewFilterChips.kt
search/src/main/kotlin/com/alfresco/content/search/SearchChipCategory.kt
search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
search/src/main/kotlin/com/alfresco/content/search/SearchResultsState.kt
search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt
search/src/main/kotlin/com/alfresco/content/search/components/ComponentCreateViewModel.kt
search/src/main/kotlin/com/alfresco/content/search/components/CreateComponentsSheet.kt
search/src/main/res/layout/sheet_component_create.xml
search/src/main/res/layout/view_check_facet_list_component.xml
search/src/main/res/layout/view_check_facet_list_row.xml
search/src/main/res/values/strings.xml

1. added chips for facet search filter

Mobileapps 984

---

search/src/main/kotlin/com/alfresco/content/search/SearchChipCategory.kt
search/src/main/kotlin/com/alfresco/content/search/components/CreateComponentsSheet.kt
search/src/main/kotlin/com/alfresco/content/search/components/ListViewFacetCheckRow.kt
search/src/main/res/layout/sheet_component_create.xml
search/src/main/res/layout/view_check_list_component.xml
search/src/main/res/layout/view_facet_check_list_component.xml
search/src/main/res/layout/view_radio_list_component.xml
search/src/main/res/layout/view_text_component.xml
search/src/main/res/values/strings.xml

1. Title drawer is not showing
2. Search input field will show if more than 10 items
3. Implement scroll to facet component value if item is more than 10.

Mobileapps 988

---

search/src/main/kotlin/com/alfresco/content/search/SearchChipCategory.kt

reset filter and showing results

Mobileapps-949

---

search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt

Mobileapps-928

---

data/src/main/kotlin/com/alfresco/content/data/SearchRepository.kt
search/src/main/assets/app.config.json
search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt

MOBILEAPPS-1010

---

listview/src/main/res/layout/fragment_list.xml

- fixed simultaneously 2 open file issue

MOBILEAPPS-1005

---

capture/src/main/AndroidManifest.xml
capture/src/main/kotlin/com/alfresco/capture/PreviewActivity.kt
capture/src/main/kotlin/com/alfresco/capture/PreviewFragment.kt
capture/src/main/kotlin/com/alfresco/capture/SaveFragment.kt
capture/src/main/res/layout/activity_preview.xml
capture/src/main/res/layout/fragment_preview.xml
capture/src/main/res/navigation/nav_capture.xml
common/src/main/kotlin/com/alfresco/content/NavControllerExt.kt

- update view of preview screen for capture media

Mobileapps-1013

---

data/src/main/kotlin/com/alfresco/content/data/FacetContext.kt
search/src/main/kotlin/com/alfresco/content/search/SearchResultsState.kt
search/src/main/res/layout/fragment_recent_search.xml
search/src/main/res/layout/fragment_search.xml

Mobileapps-1016

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadFiles.kt
actions/src/main/kotlin/com/alfresco/content/actions/CreateActionsSheet.kt
actions/src/main/res/drawable/ic_action_upload.xml
actions/src/main/res/values/strings.xml
search/src/main/assets/app.config.json
search/src/main/kotlin/com/alfresco/content/search/ListViewFilterChips.kt
search/src/main/kotlin/com/alfresco/content/search/SearchResultsState.kt
search/src/main/res/values/strings.xml

- upload files
- updated app json
- changed search facet logic
- bug fixing

Mobileapps 1020

---

search/src/main/kotlin/com/alfresco/content/search/ListViewFilterChips.kt
search/src/main/res/values-de/strings.xml
search/src/main/res/values-es/strings.xml
search/src/main/res/values-fr/strings.xml
search/src/main/res/values-it/strings.xml
search/src/main/res/values-nl/strings.xml
search/src/main/res/values/strings.xml

Mobileapps-1033

---

app/src/main/java/com/alfresco/content/app/fragment/SettingsFragment.kt
auth/src/main/kotlin/com/alfresco/auth/activity/LogoutActivity.kt

Mobileapps-1038

---

data/src/main/kotlin/com/alfresco/content/data/FacetContext.kt
data/src/main/kotlin/com/alfresco/content/data/StringExt.kt
search/src/main/kotlin/com/alfresco/content/search/SearchResultsState.kt
search/src/main/kotlin/com/alfresco/content/search/components/ComponentCreateViewModel.kt
search/src/main/kotlin/com/alfresco/content/search/components/CreateComponentsSheet.kt
search/src/main/res/values-de/strings.xml
search/src/main/res/values-es/strings.xml
search/src/main/res/values-fr/strings.xml
search/src/main/res/values-it/strings.xml
search/src/main/res/values-nl/strings.xml
search/src/main/res/values/strings.xml

- added KB unit for content size and file size

Mobileapps 1042

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionExtension.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadExtensionFiles.kt
actions/src/main/res/values/strings.xml
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/alfresco/content/app/activity/ExtensionActivity.kt
app/src/main/java/com/alfresco/content/app/activity/LoginActivity.kt
app/src/main/res/values/strings.xml
auth/src/main/kotlin/com/alfresco/auth/activity/LoginViewModel.kt
auth/src/main/res/values/strings.xml
browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewModel.kt
data/src/main/kotlin/com/alfresco/content/data/BrowseRepository.kt
listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt
listview/src/main/kotlin/com/alfresco/content/listview/ListViewRow.kt
shareextension/build.gradle
shareextension/src/main/kotlin/com/alfresco/content/shareextension/BrowseExtensionFragment.kt
shareextension/src/main/kotlin/com/alfresco/content/shareextension/ExtensionFragment.kt
shareextension/src/main/res/values-de/strings.xml
shareextension/src/main/res/values-es/strings.xml
shareextension/src/main/res/values-fr/strings.xml
shareextension/src/main/res/values-it/strings.xml
shareextension/src/main/res/values-nl/strings.xml
shareextension/src/main/res/values/strings.xml

- uploading files in the root directory

Mobileapps-1056

---

app/src/main/java/com/alfresco/content/app/activity/ExtensionActivity.kt
app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
app/src/main/res/navigation/nav_share_extension.xml
browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewModel.kt
browse/src/main/res/values/values.xml
common/src/main/kotlin/com/alfresco/content/NavControllerExt.kt
shareextension/src/main/kotlin/com/alfresco/content/shareextension/BrowseExtensionFragment.kt
shareextension/src/main/kotlin/com/alfresco/content/shareextension/ExtensionFragment.kt

MOBILEAPPS-1057

---

browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewModel.kt
common/src/main/kotlin/com/alfresco/content/NavControllerExt.kt
shareextension/src/main/kotlin/com/alfresco/content/shareextension/BrowseExtensionFragment.kt

- upload files in a child folder

Mobileapps-1058

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/alfresco/content/app/activity/ExtensionActivity.kt
app/src/main/res/navigation/nav_share_extension.xml
auth/src/main/res/values/strings.xml
browse/src/main/kotlin/com/alfresco/content/browse/BrowseFragment.kt
common/src/main/kotlin/com/alfresco/content/NavControllerExt.kt
data/src/main/kotlin/com/alfresco/content/data/Entry.kt
data/src/main/kotlin/com/alfresco/content/data/ResponsePaging.kt
data/src/main/kotlin/com/alfresco/content/data/SearchRepository.kt
search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
search/src/main/kotlin/com/alfresco/content/search/SearchResultsFragment.kt
search/src/main/kotlin/com/alfresco/content/search/SearchResultsState.kt
search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt
shareextension/src/main/kotlin/com/alfresco/content/shareextension/BrowseExtensionFragment.kt

- search enabled for extension folders,
- fixed app crash if user not logged in even for a single time
- fixed crash if user click on any file

MOBILEAPPS-1082

---

actions/src/main/AndroidManifest.xml
actions/src/main/kotlin/com/alfresco/content/actions/ActionPermission.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadExtensionFiles.kt
actions/src/main/res/values/strings.xml
app/src/main/java/com/alfresco/content/app/activity/ExtensionActivity.kt
app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
app/src/main/res/values/strings.xml
browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewModel.kt
data/src/main/kotlin/com/alfresco/content/data/BrowseRepository.kt
data/src/main/kotlin/com/alfresco/content/data/OfflineRepository.kt
listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt
shareextension/src/main/kotlin/com/alfresco/content/shareextension/BrowseExtensionFragment.kt
shareextension/src/main/kotlin/com/alfresco/content/shareextension/ExtensionFragment.kt

- fixed upload issue on session expire

Mobileapps-1092

---

app/src/main/java/com/alfresco/content/app/activity/ExtensionActivity.kt

- fixed issue show internet unavailable prompt issue if no network

Mobileapps-1090

---

search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt

Mobileapps-1097

---

app/src/main/java/com/alfresco/content/app/activity/ExtensionActivity.kt

- fixed redirection if user not logged in

Mobileapps-1089

---

app/src/main/AndroidManifest.xml
listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt
listview/src/main/kotlin/com/alfresco/content/listview/ListViewRow.kt

- fixed upload button disabled issue if there is no data

Mobileapps-1098

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadExtensionFiles.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadFiles.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadMedia.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/alfresco/content/app/activity/ExtensionActivity.kt
app/src/main/res/navigation/nav_bottom.xml
auth/src/main/res/values/strings.xml
browse/src/main/kotlin/com/alfresco/content/browse/BrowseFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewState.kt
browse/src/main/kotlin/com/alfresco/content/browse/transfer/TransferFilesFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/transfer/TransferFilesViewModel.kt
browse/src/main/res/values/strings.xml
common/src/main/kotlin/com/alfresco/content/NavControllerExt.kt
data/objectbox-models/default.json
data/src/main/kotlin/com/alfresco/content/data/Entry.kt
data/src/main/kotlin/com/alfresco/content/data/OfflineRepository.kt
listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt
listview/src/main/res/drawable/ic_upload.xml
listview/src/main/res/layout/fragment_list.xml
listview/src/main/res/layout/fragment_transfer_files_list.xml
listview/src/main/res/values/strings.xml
search/src/main/kotlin/com/alfresco/content/search/SearchResultsFragment.kt
shareextension/src/main/kotlin/com/alfresco/content/shareextension/BrowseExtensionFragment.kt
shareextension/src/main/kotlin/com/alfresco/content/shareextension/TransferFilesFragment.kt
shareextension/src/main/kotlin/com/alfresco/content/shareextension/TransferFilesViewModel.kt

- uploading file banner
- added transfer screen

Mobileapps 1083

---

actions/src/main/res/values-es/strings.xml
app/src/main/res/values-es/strings.xml
auth/src/main/res/values-es/strings.xml
browse/src/main/res/values-es/strings.xml
capture/src/main/res/values-es/strings.xml
download/src/main/res/values-es/strings.xml
listview/src/main/res/values-es/strings.xml
search/src/main/res/values-es/strings.xml
shareextension/src/main/res/values-es/strings.xml
viewer-media/src/main/res/values-es/strings.xml
viewer-pdf/src/main/res/values-es/strings.xml
viewer/src/main/res/values-es/strings.xml

Files in Spanish for ANDROID ADW 1.2

LOC-354 partial fix Localised files in ES (Spanish)

---

actions/src/main/res/values-it/strings.xml
actions/src/main/res/values/strings.xml
app/src/main/res/navigation/nav_bottom.xml

localization_fix

---

browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewModel.kt
browse/src/main/res/drawable/ic_create_new_folder.xml
browse/src/main/res/menu/menu_browse_extension.xml
shareextension/src/main/kotlin/com/alfresco/content/shareextension/BrowseExtensionFragment.kt

- added create new folder feature on the extension

Mobileapps 1126

---

search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt

- enable global search for the extension

Mobileapps-1118

---

app/src/main/res/navigation/nav_bottom.xml
data/src/main/kotlin/com/alfresco/content/data/SearchRepository.kt

- fixed contextual search issue

Mobileapps-1107

---

search/src/main/assets/app.config.json

- fixed label in app config json

Mobileapps-1108

---

listview/src/main/res/layout/fragment_move_list.xml
listview/src/main/res/values/strings.xml

- changed the move button name

MOBILEAPPS-1161

---

actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModel.kt
actions/src/main/res/values/strings.xml

- updated the order of the list of actions

Mobileapps-1163

---

actions/src/main/kotlin/com/alfresco/content/actions/CreateFolderDialog.kt
actions/src/main/res/values/strings.xml

- updated the rename popup dialog text

MOBILEAPPS-1160

---

listview/src/main/res/layout/fragment_extension_list.xml
shareextension/src/main/kotlin/com/alfresco/content/shareextension/BrowseExtensionFragment.kt

- added cancel functionality in the extension screen

MOBILEAPPS-1167

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionMoveFragment.kt
app/src/main/java/com/alfresco/content/app/activity/MoveActivity.kt
app/src/main/res/layout/activity_move.xml
app/src/main/res/navigation/nav_bottom.xml
app/src/main/res/navigation/nav_share_extension.xml
common/src/main/kotlin/com/alfresco/content/NavControllerExt.kt
search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
search/src/main/kotlin/com/alfresco/content/search/SearchResultsState.kt

Mobileapps-1157

---

app/src/main/java/com/alfresco/content/app/activity/BaseActivity.kt
listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt

Mobileapps-1175

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionUpdateFileFolder.kt
listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt

- removed the extension from file while renaming

Mobileapps 1197

---

app/src/main/res/navigation/nav_bottom.xml
app/src/main/res/navigation/nav_share_extension.xml
common/src/main/kotlin/com/alfresco/content/NavControllerExt.kt
search/src/main/kotlin/com/alfresco/content/search/SearchResultsFragment.kt

This reverts commit 19409fccfae642af2e01115864e283c91f8aba2a.

Revert "fixed title on search while sharing thorugh extension (#115)"

---

actions/src/main/res/values-de/strings.xml
actions/src/main/res/values-es/strings.xml
actions/src/main/res/values-fr/strings.xml
actions/src/main/res/values-it/strings.xml
actions/src/main/res/values-nl/strings.xml
app/src/main/res/values-de/strings.xml
auth/src/main/res/values-de/strings.xml
auth/src/main/res/values-es/strings.xml
auth/src/main/res/values-fr/strings.xml
auth/src/main/res/values-it/strings.xml
auth/src/main/res/values-nl/strings.xml
auth/src/main/res/values/strings.xml
browse/src/main/res/values-es/strings.xml
common/src/main/res/values-fr/strings.xml
common/src/main/res/values-it/strings.xml
common/src/main/res/values-nl/strings.xml
listview/src/main/res/values-de/strings.xml
listview/src/main/res/values-es/strings.xml
listview/src/main/res/values-fr/strings.xml
listview/src/main/res/values-it/strings.xml
listview/src/main/res/values-nl/strings.xml
search/src/main/res/values-de/strings.xml
search/src/main/res/values-es/strings.xml
search/src/main/res/values-fr/strings.xml
search/src/main/res/values-it/strings.xml
search/src/main/res/values-nl/strings.xml
shareextension/src/main/res/values-de/strings.xml

Localized UI files for the ADW Android mobile app in 5 languages

LOC-371_localised_UI

---

actions/src/main/kotlin/com/alfresco/content/actions/Action.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionCaptureMedia.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionCreateFolder.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionDelete.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionDownload.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionFavorite.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionMoveFilesFolders.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionOffline.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionOpenWith.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionUpdateFileFolder.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadFiles.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionUploadMedia.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheet.kt
actions/src/main/kotlin/com/alfresco/content/actions/CreateActionsSheet.kt
app/src/main/java/com/alfresco/content/app/AlfrescoApplication.kt
data/src/main/kotlin/com/alfresco/content/data/AnalyticsManager.kt
data/src/main/kotlin/com/alfresco/content/data/AnalyticsRepository.kt
search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
viewer/src/main/kotlin/com/alfresco/content/viewer/ViewerViewModel.kt

MOBILEAPPS-1237

---

download/src/main/kotlin/com/alfresco/download/DownloadMonitor.kt

- Android 12 crash issue fixed on downloading the file

MOBILEAPPS-1381

---

browse/src/main/kotlin/com/alfresco/content/browse/tasks/attachments/AttachedFilesFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/comments/CommentsFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModelExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewState.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewModel.kt
browse/src/main/res/layout/fragment_comments.xml
browse/src/main/res/layout/fragment_task_detail.xml
browse/src/main/res/values/strings.xml
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt

- added functionality to complete the task.

MOBILEAPPS-1310

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionOpenWith.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModelExtension.kt
data/src/main/kotlin/com/alfresco/content/data/Entry.kt

- Fixed issue If user cancels the downloading and then not able to see it's preview

MOBILEAPPS-1383

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionOpenWith.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksFragment.kt
browse/src/main/res/layout/fragment_task_detail.xml
browse/src/main/res/values/strings.xml
data/src/main/kotlin/com/alfresco/content/data/AnalyticsManager.kt
data/src/main/kotlin/com/alfresco/content/data/AnalyticsRepository.kt
listview/src/main/kotlin/com/alfresco/content/listview/TextViewExt.kt
listview/src/main/kotlin/com/alfresco/content/listview/tasks/TaskListFragment.kt

MOBILEAPPS-1388

---

app/src/main/res/values-fr/strings.xml
app/src/main/res/values-nl/strings.xml
browse/src/main/res/values-de/strings.xml
browse/src/main/res/values-es/strings.xml
browse/src/main/res/values-fr/strings.xml
browse/src/main/res/values-it/strings.xml
browse/src/main/res/values-nl/strings.xml
listview/src/main/res/values-de/strings.xml
listview/src/main/res/values-es/strings.xml
listview/src/main/res/values-fr/strings.xml
listview/src/main/res/values-it/strings.xml
listview/src/main/res/values-nl/strings.xml

@gl-lovekesh please merge these final files into main branch.

LOC-384 _ second round of updates to UI files in 5 languages

---

app/src/main/java/com/alfresco/content/app/activity/LoginActivity.kt
app/src/main/java/com/alfresco/content/app/widget/ActionBarController.kt
app/src/main/java/com/alfresco/content/app/widget/ActionBarLayout.kt
app/src/main/res/layout/layout_toolbar.xml
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewModel.kt
listview/src/main/kotlin/com/alfresco/content/listview/tasks/TaskListFragment.kt

- added account screen navigation from task screen

added account screen navigation from task screen

---

browse/src/main/res/values-de/strings.xml
browse/src/main/res/values-es/strings.xml
browse/src/main/res/values-fr/strings.xml
browse/src/main/res/values-it/strings.xml
browse/src/main/res/values-nl/strings.xml

Hello @gl-lovekesh please merge these Android updated files

LOC-384 - 3rd update to the UI in 5 languages

---

browse/src/main/kotlin/com/alfresco/content/browse/tasks/comments/ListViewCommentRow.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
browse/src/main/res/layout/fragment_task_detail.xml
common/src/main/kotlin/com/alfresco/content/ZoneDateTimeExt.kt
component/src/main/java/com/alfresco/content/component/ComponentViewModel.kt
data/src/main/kotlin/com/alfresco/content/data/TaskEntry.kt

- added feature to save due date on task detail

MOBILEAPPS-1404

---

browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewModel.kt

- fixed the scrolling issue on the task list screen

Mobileapps 1455

---

browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewModel.kt
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt

- added API to fetch the APS user profile data

MOBILEAPPS-1400

---

browse/src/main/kotlin/com/alfresco/content/browse/tasks/BaseDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/attachments/AttachedFilesFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/attachments/ListViewAttachmentRow.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewState.kt
browse/src/main/res/layout/fragment_attached_files.xml
browse/src/main/res/layout/view_list_attachment_row.xml
browse/src/main/res/values/strings.xml
data/src/main/kotlin/com/alfresco/content/data/AnalyticsRepository.kt
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt

- added feature to delete the content related to task

MOBILEAPPS-1430

---

browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModelExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewState.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewState.kt
data/src/main/kotlin/com/alfresco/content/data/TaskEntry.kt

- Fixed mark as complete issue
- Fixed issue of back-button discard changes dialog if there is no change

Mobileapps 1473

---

browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
browse/src/main/res/layout/fragment_task_detail.xml

MOBILEAPPS-1477

---

browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewState.kt
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt

- fixed crash if APS user is not enabled

MOBILEAPPS-1476

---

actions/src/main/kotlin/com/alfresco/content/actions/CreateTaskDialog.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/BaseDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/attachments/ListViewAttachmentRow.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
common/src/main/kotlin/com/alfresco/content/common/StringExt.kt
common/src/main/res/values-night/colors.xml
component/src/main/java/com/alfresco/content/component/SearchUserComponentSheet.kt
listview/src/main/kotlin/com/alfresco/content/listview/TextViewExt.kt

- applied listener on delete icon for deleting the attachment related to task

MOBILEAPPS-1480

---

browse/src/main/kotlin/com/alfresco/content/browse/tasks/TaskViewerActivity.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/attachments/AttachedFilesFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModelExtension.kt
browse/src/main/res/layout/activity_task_viewer.xml
browse/src/main/res/values-de/strings.xml
browse/src/main/res/values-es/strings.xml
browse/src/main/res/values-fr/strings.xml
browse/src/main/res/values-it/strings.xml
browse/src/main/res/values-nl/strings.xml
browse/src/main/res/values/strings.xml
data/src/main/kotlin/com/alfresco/content/data/ResponseList.kt
data/src/main/kotlin/com/alfresco/content/data/TaskEntry.kt
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
listview/src/main/kotlin/com/alfresco/content/listview/tasks/ListViewTaskRow.kt
listview/src/main/res/layout/view_list_task_row.xml
listview/src/main/res/values-de/strings.xml
listview/src/main/res/values-es/strings.xml
listview/src/main/res/values-fr/strings.xml
listview/src/main/res/values-it/strings.xml
listview/src/main/res/values-nl/strings.xml
listview/src/main/res/values/strings.xml

- fixed the accessibility read issue as group

Mobileapps 1461

---

actions/src/main/res/values-de/strings.xml
actions/src/main/res/values-es/strings.xml
actions/src/main/res/values-fr/strings.xml
actions/src/main/res/values-it/strings.xml
actions/src/main/res/values-nl/strings.xml
browse/src/main/res/values-de/strings.xml
browse/src/main/res/values-es/strings.xml
browse/src/main/res/values-fr/strings.xml
browse/src/main/res/values-it/strings.xml
browse/src/main/res/values-nl/strings.xml
common/src/main/res/values-it/strings.xml
component/src/main/res/values-de/strings.xml
component/src/main/res/values-es/strings.xml
component/src/main/res/values-fr/strings.xml
component/src/main/res/values-it/strings.xml
component/src/main/res/values-nl/strings.xml
listview/src/main/res/values-de/strings.xml
listview/src/main/res/values-es/strings.xml
listview/src/main/res/values-fr/strings.xml
listview/src/main/res/values-it/strings.xml
listview/src/main/res/values-nl/strings.xml

Hello @gl-lovekesh please can you merge these files for Android?  Please let me know if you have any questions.

LOC-392_UI updates fro Android ADW 1.5.0

---

auth/src/main/res/layout/fragment_auth_help.xml
auth/src/main/res/values/strings.xml
build.gradle

- added missing string for close button

MOBILEAPPS-1566

---

app/src/main/res/layout/layout_toolbar.xml
app/src/main/res/layout/view_profile_icon.xml
app/src/main/res/values/strings.xml
listview/src/main/kotlin/com/alfresco/content/listview/ListViewGroupHeader.kt
listview/src/main/kotlin/com/alfresco/content/listview/ListViewRow.kt
listview/src/main/res/layout/view_list_group_header.xml
listview/src/main/res/layout/view_list_row.xml
listview/src/main/res/values/strings.xml

- added accessibility for recent screen

MOBILEAPPS-1570

---

app/src/main/java/com/alfresco/content/app/activity/SettingsActivity.kt
app/src/main/java/com/alfresco/content/app/fragment/SettingsFragment.kt
app/src/main/java/com/alfresco/content/app/widget/AccountPreference.kt
app/src/main/res/layout/layout_pref_account.xml
app/src/main/res/values/strings.xml

- added accessibility text on the settings page

MOBILEAPPS-1556

---

auth/src/main/kotlin/com/alfresco/auth/activity/LoginActivity.kt
auth/src/main/kotlin/com/alfresco/auth/fragments/HelpFragment.kt
auth/src/main/res/layout/fragment_auth_help.xml
auth/src/main/res/values/strings.xml
browse/src/main/kotlin/com/alfresco/content/browse/FavoritesFragment.kt
browse/src/main/res/layout/fragment_favorites.xml
component/src/main/java/com/alfresco/content/component/ComponentSheet.kt
component/src/main/res/layout/view_radio_list_row.xml

- added accessibility for task list screen component

MOBILEAPPS-1574

---

actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsBarFragment.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheet.kt
actions/src/main/res/layout/sheet_action_list.xml
actions/src/main/res/layout/view_action_list_row.xml
auth/src/main/kotlin/com/alfresco/auth/fragments/HelpFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/preview/LocalPreviewActivity.kt
capture/src/main/kotlin/com/alfresco/capture/PreviewActivity.kt
common/src/main/res/values/strings.xml
listview/src/main/res/values/strings.xml
viewer/src/main/kotlin/com/alfresco/content/viewer/ViewerActivity.kt

- added accessibility for file preview

MOBILEAPPS-1554

---

browse/src/main/kotlin/com/alfresco/content/browse/BrowseFragment.kt
common/src/main/res/values/strings.xml

- added accessibility browse option

MOBILEAPPS-1548

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionListRow.kt
app/src/main/java/com/alfresco/content/app/widget/ActionBarController.kt
app/src/main/java/com/alfresco/content/app/widget/ActionBarLayout.kt
app/src/main/res/layout/layout_toolbar.xml
browse/src/main/kotlin/com/alfresco/content/browse/BrowseFragment.kt
browse/src/main/res/layout/fragment_attached_files.xml
common/src/main/res/values/strings.xml
data/src/main/kotlin/com/alfresco/content/data/AnalyticsRepository.kt
listview/src/main/res/layout/fragment_list.xml
listview/src/main/res/layout/fragment_task_list.xml

- accessibility added for navigate folder

MOBILEAPPS-1544

---

app/src/main/res/layout/layout_toolbar.xml
component/src/main/res/layout/view_check_list_row.xml
component/src/main/res/layout/view_number_range_component.xml
search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
search/src/main/res/layout/fragment_search.xml
search/src/main/res/values/strings.xml
theme/src/main/res/values/colors.xml

- added accessibility for search screen

MOBIELAPPS-1542

---

app/src/main/AndroidManifest.xml

MOBILEAPPS-1629

---

app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
browse/src/main/kotlin/com/alfresco/content/browse/BrowseFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewState.kt
browse/src/main/kotlin/com/alfresco/content/browse/menu/BrowseMenuFragment.kt
data/src/main/kotlin/com/alfresco/content/data/BrowseRepository.kt
data/src/main/kotlin/com/alfresco/content/data/ResponsePaging.kt
data/src/main/kotlin/com/alfresco/content/data/Source.kt
viewer/src/main/kotlin/com/alfresco/content/viewer/ViewerFragment.kt

- get folder name from source to show as the title on the preview screen

MOBILEAPPS-1661

---

app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt

MOBILEAPPS-1298

---

data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt

- update the download base url

MOBILEAPPS-1673

---

data/src/main/kotlin/com/alfresco/content/data/BrowseRepository.kt
data/src/main/kotlin/com/alfresco/content/data/ResponsePaging.kt
data/src/main/kotlin/com/alfresco/content/data/Source.kt

- fixed title on personal files

MOBILEAPPS-1674

---

browse/src/main/kotlin/com/alfresco/content/browse/offline/OfflineFragment.kt
data/src/main/kotlin/com/alfresco/content/data/OfflineRepository.kt
data/src/main/kotlin/com/alfresco/content/data/ResponsePaging.kt
data/src/main/kotlin/com/alfresco/content/data/SearchRepository.kt
listview/src/main/kotlin/com/alfresco/content/listview/EntryListener.kt
search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt

- added offline search for the users if not connected over network

Mobileapps 1684

---

data/src/main/kotlin/com/alfresco/content/data/CommentEntry.kt

added initial as me if logged in user commented in list

MOBILEAPPS-1675

---

actions/src/main/kotlin/com/alfresco/content/actions/Action.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionCreateFolder.kt
app/src/main/java/com/alfresco/content/app/activity/ExtensionActivity.kt
auth/src/main/kotlin/com/alfresco/ui/SplashActivity.kt
common/src/main/res/values/strings.xml
data/src/main/kotlin/com/alfresco/content/data/BrowseRepository.kt
viewer-pdf/src/main/kotlin/com/alfresco/content/viewer/pdf/PdfViewerViewModel.kt

- removed the auto rename folder from existing app

MOBILEAPPS-1138

---

browse/src/main/assets/task.filters.json
browse/src/main/kotlin/com/alfresco/content/browse/processes/list/ProcessesFragment.kt
component/src/main/java/com/alfresco/content/component/ComponentOptions.kt
component/src/main/res/values/strings.xml
data/src/main/kotlin/com/alfresco/content/data/FilterOptions.kt
data/src/main/kotlin/com/alfresco/content/data/payloads/TaskProcessFiltersPayload.kt
listview/src/main/kotlin/com/alfresco/content/listview/processes/ProcessListFragment.kt

added all status in the tasks filter

MobileApps-1775

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionStartProcess.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModel.kt
actions/src/main/res/values/strings.xml
app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
build.gradle
data/src/main/kotlin/com/alfresco/content/data/Settings.kt
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
data/src/main/kotlin/com/alfresco/content/data/payloads/SystemPropertiesEntry.kt
listview/src/main/res/layout/fragment_process_list.xml

- added option to start the process if APS is enabled

MOBILEAPPS-1727

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionStartProcess.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheet.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModel.kt
actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsSheet.kt
actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsState.kt
actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsViewModel.kt
actions/src/main/res/values/strings.xml
data/objectbox-models/default.json
data/src/main/kotlin/com/alfresco/content/data/Entry.kt
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
data/src/main/kotlin/com/alfresco/content/data/payloads/LinkContentPayload.kt

- Link ADW content to Processes

link content to processes

---

actions/src/main/kotlin/com/alfresco/content/actions/ListRowProcessDefinitions.kt
actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsSheet.kt
actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsState.kt
actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsViewModel.kt
actions/src/main/res/layout/view_process_definitions_list_row.xml
app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
data/objectbox-models/default.json.bak
data/src/main/kotlin/com/alfresco/content/data/ProcessDefinitionDataEntry.kt
data/src/main/kotlin/com/alfresco/content/data/ResponseListProcessDefinitions.kt
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt

- showing list of process definitions

MOBILEAPPS-1729

---

app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt

- start process will show only if user is enabled for APS

MOBILEAPPS-1791

---

actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheet.kt
actions/src/main/kotlin/com/alfresco/content/actions/ProcessDefinitionsSheet.kt

- fixed accessibility and scroll issue

MOBILEAPPS-1802

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionCreateTask.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionUpdateNameDescription.kt
actions/src/main/kotlin/com/alfresco/content/actions/CreateTaskDialog.kt
actions/src/main/kotlin/com/alfresco/content/actions/ListRowProcessDefinitions.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewState.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/sheet/ProcessDefinitionsSheet.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/sheet/ProcessDefinitionsState.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/sheet/ProcessDefinitionsViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
component/src/main/java/com/alfresco/content/component/ComponentSheet.kt
component/src/main/java/com/alfresco/content/component/ComponentType.kt
data/src/main/kotlin/com/alfresco/content/data/ProcessEntry.kt
data/src/main/kotlin/com/alfresco/content/data/ResponseListProcessDefinitions.kt
data/src/main/kotlin/com/alfresco/content/data/RuntimeProcessDefinitionDataEntry.kt
listview/src/main/kotlin/com/alfresco/content/listview/processes/ListRowProcessDefinitions.kt

added due date, priority, name and description components on process details

Mobileapps-1732

---

browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewState.kt
data/src/main/kotlin/com/alfresco/content/data/ProcessEntry.kt
gradle/libs.versions.toml

- added dialog before starting workflow if attachments are not uploaded yet.

MOBILEAPPS-1736

---

data/src/main/kotlin/com/alfresco/content/data/BrowseRepository.kt
data/src/main/kotlin/com/alfresco/content/data/ResponsePaging.kt
data/src/main/kotlin/com/alfresco/content/data/Source.kt

MOBILEAPPS-1858

---

component/src/main/java/com/alfresco/content/component/SearchUserGroupComponentViewModel.kt
gradle/libs.versions.toml

Task assignee fix

---

browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailFragment.kt
data/src/main/kotlin/com/alfresco/content/data/Entry.kt
viewer/src/main/kotlin/com/alfresco/content/viewer/ViewerActivity.kt

MOBILEAPPS-1817

---

browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewState.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/list/ProcessesFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/list/ProcessesViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewModel.kt
browse/src/main/res/drawable/ic_forward_nav.xml
browse/src/main/res/layout/fragment_task_detail.xml
browse/src/main/res/values/strings.xml
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
data/src/main/kotlin/com/alfresco/content/data/payloads/TaskProcessFiltersPayload.kt
listview/src/main/kotlin/com/alfresco/content/listview/processes/ProcessListFragment.kt
viewer/src/main/kotlin/com/alfresco/content/viewer/ViewerActivity.kt

- added details related to workflows

MOBILEAPPS-1814

---

browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewState.kt
browse/src/main/res/navigation/nav_task_paths.xml
browse/src/main/res/values-de/strings.xml
browse/src/main/res/values-es/strings.xml
browse/src/main/res/values-fr/strings.xml
browse/src/main/res/values-it/strings.xml
browse/src/main/res/values-nl/strings.xml
browse/src/main/res/values/strings.xml
listview/src/main/kotlin/com/alfresco/content/listview/tasks/TaskListFragment.kt
listview/src/main/res/layout/fragment_task_list.xml
listview/src/main/res/values-de/strings.xml
listview/src/main/res/values-es/strings.xml
listview/src/main/res/values-fr/strings.xml
listview/src/main/res/values-it/strings.xml
listview/src/main/res/values-nl/strings.xml
listview/src/main/res/values/strings.xml

- added list of tasks related to workflow

MOBILEAPPS-1812

---

browse/src/main/res/values-de/strings.xml
browse/src/main/res/values-es/strings.xml
browse/src/main/res/values-fr/strings.xml
browse/src/main/res/values-it/strings.xml
browse/src/main/res/values-nl/strings.xml
component/src/main/res/values-de/strings.xml
component/src/main/res/values-es/strings.xml
component/src/main/res/values-fr/strings.xml
component/src/main/res/values-it/strings.xml
component/src/main/res/values-nl/strings.xml

Hello @aman-alfresco Please merge the Android strings for the ADW mobile app.  Hope all are OK.

LOC-439  ANDROID UI strings updated

---

actions/src/main/res/values/strings.xml
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewState.kt
browse/src/main/res/layout/fragment_task_detail.xml
browse/src/main/res/menu/menu_workflow_task_detail.xml
browse/src/main/res/values-de/strings.xml
browse/src/main/res/values-es/strings.xml
browse/src/main/res/values-fr/strings.xml
browse/src/main/res/values-it/strings.xml
browse/src/main/res/values-nl/strings.xml
common/src/main/res/values-de/strings.xml
common/src/main/res/values-es/strings.xml
common/src/main/res/values-fr/strings.xml
common/src/main/res/values-it/strings.xml
common/src/main/res/values-nl/strings.xml
data/objectbox-models/default.json.bak
data/src/main/kotlin/com/alfresco/content/data/FormVariables.kt
data/src/main/kotlin/com/alfresco/content/data/ProcessEntry.kt
data/src/main/kotlin/com/alfresco/content/data/TaskEntry.kt
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt

- added claim and release for pooled processes

MOBILEAPPS-1816

---

browse/src/main/assets/task.filters.json
browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/details/ProcessDetailViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/BaseDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewModel.kt
component/src/main/java/com/alfresco/content/component/searchusergroup/SearchUserGroupComponentState.kt
component/src/main/res/values/strings.xml
data/src/main/kotlin/com/alfresco/content/data/ProcessEntry.kt
data/src/main/kotlin/com/alfresco/content/data/payloads/TaskProcessFiltersPayload.kt

MOBILEAPPS-1920

---

browse/src/main/kotlin/com/alfresco/content/browse/processes/status/TaskStatusFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModelExtension.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewState.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/list/TasksViewState.kt
browse/src/main/res/layout/view_layout_negative_outcome.xml
browse/src/main/res/layout/view_layout_positive_outcome.xml
browse/src/main/res/menu/menu_workflow_task_detail.xml
common/src/main/kotlin/com/alfresco/content/ZoneDateTimeExt.kt
common/src/main/kotlin/com/alfresco/content/common/TextViewExt.kt
data/src/main/kotlin/com/alfresco/content/data/TaskEntry.kt
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
listview/src/main/kotlin/com/alfresco/content/listview/processes/ListViewProcessRow.kt
listview/src/main/kotlin/com/alfresco/content/listview/processes/ProcessListFragment.kt
listview/src/main/kotlin/com/alfresco/content/listview/tasks/ListViewTaskRow.kt
listview/src/main/kotlin/com/alfresco/content/listview/tasks/TaskListFragment.kt
listview/src/main/res/layout/view_list_process_row.xml
listview/src/main/res/layout/view_list_task_row.xml

- added date and time on task list

time_stamp_added

---

common/src/main/kotlin/com/alfresco/content/network/ConnectivityTracker.kt
search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt

Reverts Alfresco/alfresco-mobile-workspace-android#264

Revert "fixed network issue"

---

common/src/main/kotlin/com/alfresco/content/network/ConnectivityTracker.kt
search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt

Reverts Alfresco/alfresco-mobile-workspace-android#265

Revert "Revert "fixed network issue""

---

listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt
listview/src/main/kotlin/com/alfresco/content/listview/ListViewRow.kt
listview/src/main/res/layout/view_list_row.xml

- added a long press gesture for the row to select multiple files
- No Unit Test cases

MOBILEAPPS-1976

---

app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
app/src/main/res/drawable/ic_cross_arrow_blue.xml
app/src/main/res/drawable/ic_more_vert_blue.xml
app/src/main/res/drawable/ic_move_blue.xml
app/src/main/res/menu/menu_action_multi_selection.xml
base-ui/src/main/res/values-night/colors.xml
base-ui/src/main/res/values/colors.xml
browse/src/main/kotlin/com/alfresco/content/browse/BrowseFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewModel.kt
browse/src/main/kotlin/com/alfresco/content/browse/FavoritesFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/offline/OfflineFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/offline/OfflineViewModel.kt
browse/src/test/java/com/alfresco/content/browse/BrowseViewModelTest.kt
common/src/main/res/values/strings.xml
gradle/libs.versions.toml
listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt
listview/src/main/kotlin/com/alfresco/content/listview/MultiSelection.kt
search/src/main/kotlin/com/alfresco/content/search/SearchResultsFragment.kt
search/src/main/kotlin/com/alfresco/content/search/SearchViewModel.kt
theme/src/main/res/drawable/ic_cross_arrow_blue.xml
theme/src/main/res/drawable/ic_cross_arrow_blue_night.xml
theme/src/main/res/values/colors.xml
theme/src/main/res/values/themes.xml

- added header component for the multi-selection

Mobileapps 1980

---

actions/build.gradle
actions/src/main/kotlin/com/alfresco/content/actions/Action.kt
actions/src/main/kotlin/com/alfresco/content/actions/ActionMoveFilesFolders.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsBarFragment.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheet.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheetExtension.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsState.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModel.kt
actions/src/test/java/com/alfresco/content/actions/ContextualActionsViewModelTest.kt
app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
app/src/main/res/navigation/nav_bottom.xml
browse/build.gradle
browse/src/main/kotlin/com/alfresco/content/browse/BrowseFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewState.kt
browse/src/main/kotlin/com/alfresco/content/browse/FavoritesFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/offline/OfflineFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/offline/OfflineViewState.kt
data/objectbox-models/default.json
data/src/main/kotlin/com/alfresco/content/data/ContextualActionData.kt
data/src/main/kotlin/com/alfresco/content/data/Entry.kt
data/src/main/kotlin/com/alfresco/content/data/MultiSelection.kt
data/src/main/kotlin/com/alfresco/content/data/Settings.kt
gradle/libs.versions.toml
listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt
search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
search/src/main/kotlin/com/alfresco/content/search/SearchResultsFragment.kt
viewer/src/main/kotlin/com/alfresco/content/viewer/ViewerFragment.kt

- added move and favorites option for multi selection

MOBILEAPPS-1982

---

app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
data/objectbox-models/default.json.bak
listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt

- fixed multiselection rotation issue on tablet

Mobileapps 2022

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionMoveFilesFolders.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheet.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModel.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModelExtension.kt
actions/src/main/kotlin/com/alfresco/content/actions/CreateFolderDialog.kt
actions/src/main/res/values/strings.xml
app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
app/src/main/res/navigation/nav_move_paths.xml
browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewState.kt
common/src/main/kotlin/com/alfresco/content/NavControllerExt.kt
data/src/main/kotlin/com/alfresco/content/data/Entry.kt

- added a feature to move multiple files together

MOBIELAPPS-1984

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionDelete.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheet.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModel.kt
actions/src/main/res/values/strings.xml
browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewModel.kt
data/src/main/kotlin/com/alfresco/content/data/BrowseRepository.kt
data/src/main/kotlin/com/alfresco/content/data/TrashCanRepository.kt
gradle/libs.versions.toml

- added delete ,restore and forever delete actions

MOBILEAPPS-1988

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionFavorite.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheet.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModel.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModelExtension.kt
app/src/main/java/com/alfresco/content/app/activity/MoveActivity.kt
app/src/main/res/layout/activity_move.xml
app/src/main/res/layout/activity_share.xml
browse/src/main/kotlin/com/alfresco/content/browse/BrowseViewModel.kt
data/src/main/kotlin/com/alfresco/content/data/FavoritesRepository.kt
listview/src/main/kotlin/com/alfresco/content/listview/ListFragment.kt

- added multi-action for favorite

MOBILEAPPS-2033

---

actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheet.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsSheetExtension.kt
app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
app/src/main/res/values/strings.xml
build.gradle

- accessibility action sheet issue fixed

MOBILEAPPS-2038

---

app/src/main/java/com/alfresco/content/app/activity/MainActivityViewModel.kt
data/src/main/kotlin/com/alfresco/content/data/AnalyticsManager.kt
data/src/main/kotlin/com/alfresco/content/data/AuthenticationRepository.kt
data/src/main/kotlin/com/alfresco/content/data/BrowseRepository.kt
data/src/main/kotlin/com/alfresco/content/data/FavoritesRepository.kt
data/src/main/kotlin/com/alfresco/content/data/OfflineRepository.kt
data/src/main/kotlin/com/alfresco/content/data/RenditionRepository.kt
data/src/main/kotlin/com/alfresco/content/data/SearchRepository.kt
data/src/main/kotlin/com/alfresco/content/data/SharedLinksRepository.kt
data/src/main/kotlin/com/alfresco/content/data/SitesRepository.kt
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
data/src/main/kotlin/com/alfresco/content/data/TrashCanRepository.kt
session/src/main/kotlin/com/alfresco/content/session/ActionSessionInvalid.kt
session/src/main/kotlin/com/alfresco/content/session/SessionManager.kt
session/src/main/kotlin/com/alfresco/content/session/SessionNotFoundException.kt

- fixed requires session crash

MOBILEAPPS-2027

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionOffline.kt
actions/src/main/kotlin/com/alfresco/content/actions/ContextualActionsViewModel.kt
app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
app/src/main/java/com/alfresco/content/app/activity/MoveActivity.kt
browse/src/main/kotlin/com/alfresco/content/browse/BrowseFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/processes/status/TaskStatusFragment.kt
browse/src/main/kotlin/com/alfresco/content/browse/tasks/detail/TaskDetailViewModel.kt
data/src/main/kotlin/com/alfresco/content/data/OfflineRepository.kt
data/src/main/kotlin/com/alfresco/content/data/TaskRepository.kt
search/src/main/kotlin/com/alfresco/content/search/SearchFragment.kt
search/src/main/kotlin/com/alfresco/content/search/SearchResultsFragment.kt

removed workflow status and comment issue, also a fixed highlighted issue for multi-selection

MOBILEAPPS-2026

---

data/src/main/kotlin/com/alfresco/content/data/Entry.kt
gradle/libs.versions.toml

MOBILEAPPS-2042

---

app/src/main/java/com/alfresco/content/app/activity/SplashActivity.kt
auth/src/main/kotlin/com/alfresco/ui/SplashActivity.kt
data/build.gradle
data/src/main/kotlin/com/alfresco/content/data/rooted/CheckForRootWorker.kt
data/src/main/kotlin/com/alfresco/content/data/rooted/RootItemResult.kt
gradle/libs.versions.toml

- restricted app for rooted device

MOBILEAPPS-1934

---

.gitignore
account/build.gradle
account/src/main/kotlin/com/alfresco/content/account/Account.kt
account/src/main/kotlin/com/alfresco/content/account/SecureSharedPreferencesManager.kt
auth/src/main/kotlin/com/alfresco/ui/SplashActivity.kt
gradle/libs.versions.toml

- Saving credentials in keystore

MOBILEAPPS-2056

---

.github/workflows/build.yml

PMD implementation in GitHub action

PMD implementation in GitHub action

---

viewer/src/main/kotlin/com/alfresco/content/viewer/ViewerFragment.kt

- fixed progress running infinite issue

MOBIELAPPS-2121

---

actions/src/main/kotlin/com/alfresco/content/actions/ActionMoveFragment.kt
actions/src/main/kotlin/com/alfresco/content/actions/MoveResultContract.kt
app/src/main/java/com/alfresco/content/app/activity/MainActivity.kt
app/src/main/java/com/alfresco/content/app/activity/MoveActivity.kt
data/src/main/kotlin/com/alfresco/content/data/rooted/CheckForRootWorker.kt
move/src/main/java/com/alfresco/content/move/MoveFragment.kt

MOBILEAPPS-2120

---

data/src/main/kotlin/com/alfresco/content/data/payloads/FieldsData.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/FormFragment.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/components/ComposeTopBar.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/components/IntegerInputField.kt

added number component

---

data/src/main/kotlin/com/alfresco/content/data/payloads/FieldsData.kt
gradle/libs.versions.toml
process-app/build.gradle
process-app/src/main/kotlin/com/alfresco/content/process/ui/FormFragment.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/components/AmountInputField.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/components/ComposeTopBar.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/components/InputField.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/components/IntegerInputField.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/components/MultiLineInputField.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/components/SingleLineInputField.kt
process-app/src/main/res/values/strings.xml

Mobileapps 2145

---

data/src/main/kotlin/com/alfresco/content/data/payloads/FieldsData.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/FormFragment.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/components/CheckboxField.kt
process-app/src/main/res/values/strings.xml

- added checkbox component for boolean types

Mobileapps 2139

---

component/src/main/java/com/alfresco/content/component/ComponentSheet.kt
component/src/main/java/com/alfresco/content/component/ListViewActionsRow.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/components/FloatingActionButton.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/components/InputChip.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/components/PeopleField.kt
process-app/src/main/kotlin/com/alfresco/content/process/ui/composeviews/FormScrollContent.kt

- added cross button on assignee selected

MOBILEAPPS-2137

---

.gitignore
account/src/main/kotlin/com/alfresco/content/account/Account.kt
account/src/main/kotlin/com/alfresco/content/account/SecureSharedPreferencesManager.kt
app/build.gradle
app/src/main/java/com/alfresco/content/app/activity/LoginActivity.kt
app/src/main/java/com/alfresco/content/app/fragment/SettingsFragment.kt
auth/build.gradle
auth/src/main/kotlin/com/alfresco/auth/activity/LoginActivity.kt
auth/src/main/kotlin/com/alfresco/auth/activity/LoginViewModel.kt
auth/src/main/kotlin/com/alfresco/auth/activity/LogoutActivity.kt
auth/src/main/kotlin/com/alfresco/auth/config/DefaultAuthConfig.kt
auth/src/main/kotlin/com/alfresco/auth/fragments/AdvancedSettingsFragment.kt
auth/src/main/res/layout/fragment_auth_settings.xml
auth/src/main/res/values/strings.xml
component/src/main/java/com/alfresco/content/component/ComponentData.kt
gradle/libs.versions.toml
session/src/main/kotlin/com/alfresco/content/session/Session.kt
settings.gradle

ADST-422 OIDC. changes for Auth0
